ALTER TABLE slow_query_samples
    ADD COLUMN IF NOT EXISTS shared_blks_hit INTEGER,
    ADD COLUMN IF NOT EXISTS shared_blks_read INTEGER,
    ADD COLUMN IF NOT EXISTS local_blks_hit INTEGER,
    ADD COLUMN IF NOT EXISTS local_blks_read INTEGER,
    ADD COLUMN IF NOT EXISTS temp_blks_read INTEGER,
    ADD COLUMN IF NOT EXISTS temp_blks_written INTEGER,
    ADD COLUMN IF NOT EXISTS plan_user_time DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS plan_sys_time DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS exec_user_time DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS exec_sys_time DOUBLE PRECISION;
